### ISSUE TITLE
cannot support 1.3.2

### ISSUE THREAD

**Issue by qlj2009** [berichan/SysBot.PokemonScarletViolet#10]
cannot support 1.3.2

**Comment by berichan** [comment]
I'll leave this open because there's going to be others like you who can't wait, but it'll be ready once PKHeX matures on its HOME support, I'll do both updates at the same time

**Comment by berichan** [comment]
Updated as of https://github.com/berichan/SysBot.PokemonScarletViolet/commit/609f6fd42f1aed6274f6fc1b52bcca18ecc5c7b4
