### ISSUE TITLE
Appealing Discord ban

### ISSUE THREAD

**Issue by Kaminoyouni** [berichan/SysBot.PokemonScarletViolet#13]
I am unsure if this is correct contact for an appeal, I was banned from the main Berichan discord earlier this year (Late December 2022 actually). and with the release of the DLC I was hoping to reuse the bot services.

I made an error in posting certain comments in the pokemon geenral channel that should have goin into the bot chatter, and made comments to a mod that were augmentative, I felt I was just talking casually, but I should apologize none the less, and follow the rules. 

Discord account should be Kaminoyouni, unless the memory still lists me as Kaminoyouni#3026

But, if there a more correct way to appeal the ban please let me know. I appreciate your taking time to read this.

**Comment by berichan** [comment]
Unrelated to SysBot.PokemonScarletViolet
