### ISSUE TITLE
Discord unban request

### ISSUE THREAD

**Issue by Leafy008** [berichan/SysBot.PokemonScarletViolet#17]
Hello! I was recently banned from the berichan discord server, with the citation “joins hacked mon server and doesn’t like hacked mons”.

For context, it began when I asked in the scarlet and violet chat if anybody had a latios they would be willing to trade me, but was responded with somebody saying “just gen it”, referring to the pokemon generator. In response, I stated how I wanted a legitimate one, as in a latios actually caught in the game. I was then met by the message “then stop being lazy and go catch one”, followed by an image of the pokemon scarlet and violet map, with the legendary locations pointed out. In response, I stated how I only owned pokemon violet, and was unable to catch one as it is a version exclusive. Additionally, I also mentioned how nobody wanted to do a union circle at the time and how trading for it seemed like the best option for me. I was then met with the message stating how I should then find another Pokémon-related discord server that specializes more into trading, with me responding with how I didn’t know any. The other user then states “Google exists”, with me replying how I didn’t want to spend a long time searching google for another discord server that may or may not be active. They then reply on how they found one in a short amount of time that could solve my, quote-on-quote, problem. Afterwards, I was banned.

I would like for my unban to be considered if possible and, if it helps, I will refrain from using the scarlet and violet chat for trade again. My discord display name is Leafy008, and my username is the same (without the capital “L” if it matters). Thank you!

**Comment by berichan** [comment]
Issue is unrelated to this repository. Please do not use GitHub issues for unrelated personal matters.
