### ISSUE TITLE
Nicknames don't work (in some cases)

### ISSUE THREAD

**Issue by usersaurus** [berichan/SysBot.PokemonScarletViolet#22]
I'm having a weird bug when trying to put nicknames on pokemons using the !tradeSV command. I'm getting a Ditto army with different nicknames based on the IVs they have. I did:

- Estupenditto (perfect IV): no issue
- Flojitto (0 IV attack): no issue
- Lentitto (0 IV speed): nickname is not used and the received poke is called Ditto

I tried several times and always had the same issue, so looks like there's something odd with all or part of that name.

**Comment by giankenbellfore** [comment]
A nickname should resonate with the person or object it represents, capturing something meaningful or distinctive about them. For example, a nickname that doesn’t align with someone's personality or experiences may feel forced or disconnected. Additionally, the context in which a nickname is used plays a significant role. In some cases, nicknames may not work if they are applied in settings where formality or professionalism is required, or if they don't fit into the cultural [explore chicken nicknames](https://nichesnames.com/chicken-names/) or social norms of the group. To create a nickname that works, ensure it is relatable, respectful, and shared by both parties involved.

**Comment by berichan** [comment]
> I'm having a weird bug when trying to put nicknames on pokemons using the !tradeSV command. I'm getting a Ditto army with different nicknames based on the IVs they have. I did:
> 
> * Estupenditto (perfect IV): no issue
> * Flojitto (0 IV attack): no issue
> * Lentitto (0 IV speed): nickname is not used and the received poke is called Ditto
> 
> I tried several times and always had the same issue, so looks like there's something odd with all or part of that name.

I assume this is due to the GF word filter for `*tit*`, nicknames that attempt to bypass the word filter will not work.
