### ISSUE TITLE
Pokemon Special Forms Request

### ISSUE THREAD

**Issue by chrisbirie** [berichan/SysBot.PokemonScarletViolet#3]
I was wondering if it is possible to request special forms of different mons in SV?

For example, the 3 or 4 member Mausold or 3 or 2 segment Dundunsparce. I believe the functionality is available in PKHeX but wasn't sure it was available in the Twitch Bot request.

**Comment by berichan** [comment]
The bot uses [ALM](https://github.com/architdate/PKHeX-Plugins) to parse showdown sets, you can use showdown's teambuilder to validate your sets: https://play.pokemonshowdown.com/teambuilder

Maushold family of 3 is `Maushold-Three` for example.
