### ISSUE TITLE
Banned  trying to use sys bot 

### ISSUE THREAD

**Issue by ShyGirl18** [berichan/SysBot.PokemonScarletViolet#4]
I was banned yesterday. Dyno said it was for spam. I was trying to use a bot but the bot couldn't read my build. I haven't had this problem with my other builds I have for pokemon scarlet and violet. I attempted to change my showdown set but all attempts failed. The set made was complex. Adding my OT, TID and SID. I really wanted to appeal this ban but I no way of contacting a mod as I'm not in the server. I've been there since January 2022 whenI was playing animal crossing and pokemon sword. Is there anyway I could be unbanned as I've never caused any problems before? 

shygirl#1816 is my username 
In this server my name was Jay.

Tandemaus @ Leftovers
Ball: Dream 
OT: Jay
TID: 353649
SID: 1049
OTGender: Female
Language: English  
Ability: Pickup  
Level: 8  
Shiny: Yes  
Tera Type: Normal  
Timid Nature  
IVs: 5 HP / 13 Def / 18 SpA / 10 Spe  
- Echoed Voice  
- Double Hit  
- Baby-Doll Eyes  
- Play Rough

The last thing I posted before my ban was 
Tandemaus @ Leftovers  
Ability: Pickup  
Level: 8  
Shiny: Yes  
Tera Type: Normal  
Timid Nature  
IVs: 5 HP / 13 Def / 18 SpA / 10 Spe  
- Echoed Voice  
- Double Hit  
- Baby-Doll Eyes  
- Play Rough

**Comment by berichan** [comment]
Unrelated to this repository.
